
// クリエイトスライスをインポートしている
import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchCount } from './counterAPI';

// counterSliceで使用する初期値用定数 Stateの中身を指定
const initialState = {
  // 初期値を設定している
  value: 0,
  status: 'idle',
};

export const incrementAsync = createAsyncThunk(
  'counter/fetchCount',
  async (amount) => {
    const response = await fetchCount(amount);
    return response.data;
  }
);

// クリエイトスライスを定義
export const counterSlice = createSlice({
  name: 'counter',

  // 定義したinitialStateを使用
  initialState,

  // 処理郡
  reducers: {
    // インクリメントアクション (state)現在のStateを取ってきて
    increment: (state) => {
      // stateのvalueにぷらす１する
      state.value += 1;
    },
    // デクリメントアクション ()
    decrement: (state) => {
      state.value -= 1;
    },

    // 現在のstateとaction(payloadという属性を持っている *引数のようなもの)
    // actionのpayloadをstateへ追加する
    incrementByAmount: (state, action) => {
      state.value += action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(incrementAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(incrementAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.value += action.payload;
      });
  },
});

// 各関数を使用でいるようにexportする
export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// stateの値を参照できるようにexportする
export const selectCount = (state) => state.counter.value;


export const incrementIfOdd = (amount) => (dispatch, getState) => {
  const currentValue = selectCount(getState());
  if (currentValue % 2 === 1) {
    dispatch(incrementByAmount(amount));
  }
};

// app.jsで呼び出される
export default counterSlice.reducer;
